name: Build ArchISO
on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: archlinux:latest
      #env:
      #  NODE_ENV: development
      #ports:
      #  - 80
      #volumes:
      #  - my_docker_volume:/volume_mount
      options: --privileged 
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Get basic info
        run: |
          ls
          whoami
          pwd
          pacman -Syyu archiso --noconfirm
